### PR TITLE
Added support to video_demo.py to save video and fixes errors

### PR DESCRIPTION
**Pull request by racsoraul**
- Adds support for saving the labeled video in video_demo.py.
- Dockerfile-gpu adds required libs.
- Fixes Gtk errors when processing a video.
- Updated Readme with fix to **"(preview:17): Gtk-WARNING **: cannot open display: :1"** error.
- Updated run-gpu.sh to have it properly working with nvidia-docker2.

### CODE REVIEW

**Comment by madhawav** [comment]
Hi @racsoraul,

I am looking at this PR now. 

Why did you decide to change the docker image of the nvidia-docker build? Was the version already in the master branch not working in your machine? If so, what was the issue you got?

**Comment by racsoraul** [comment]
Hi @madhawav,

- When I was trying to run the `video_demo.py` I was getting an error with the `imshow` function about OpenCV not being compiled with support for Gtk:

```OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, file /opencv-3.4.0/modules/highgui/src/window.cpp, line 611```

That's why I added `libgtk2.0-dev` and `pkg-config` to the base image: https://github.com/madhawav/YOLO3-4-Py/pull/80/files#diff-ac18a3893f77fb3c6b3fabc90aa46f9fR29

- After the above was succesfully done, trying to run the `video_demo.py` would fail giving the following error: ```(preview:15): Gtk-WARNING **: cannot open display: ```, which is why I changed the `run-gpu.sh` to have access to the host X11 and display.

- With above change, one could still get the same error, but could be solved by running `xhost +x` in the host. That's why I added that in the README.md.

- With all the above, now running the script would effectively show the preview of each frame. Then, I added a few lines to the script to save the previewed video.

**Comment by woojeonghoon** [comment]
As you asked, I modified 'run-gpu.sh' and 'Dockerfile-gpu'.

Then we created a container and ran 'python3 video-demo.py ./input' inside the container.

But the same error occurs

'OpenCV Error: Unspecified error (The function is not implemented.Rebuild the library with Windows, GTK + 2.x or Carbon support.If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, file /opencv-3.4.0/modules/highgui/src/window.cpp, line 611 '

**Comment by racsoraul** [comment]
Hi @woojeonghoon!

I tried a fresh setup in a new computer and it works just fine. Maybe you're missing something when trying to replicate my changes. Try cloning my fork just to be sure.

**Comment by woojeonghoon** [comment]
@racsoraul


Thanks for the quick response !

Are you affected by the type of video you want to change?

For example, I wonder if it is possible to change only the specified type such as mp4 and avi ......

**Comment by woojeonghoon** [comment]
1. First, the folders are organized as follows. (I changed everything with your code)
1  filelist

2. Then run 'sh run-gpu.sh'.

3. When I run it, it goes into the Container created by docker run.

4. When I type 'ls' it consists of:
2  ls

5. Here I did 'cat video_demo.py'

Then
The video_demo.py file was before the change.


6.
So I changed video_demo.py to your source and ran 'python3 video_demo.py'.

At this time
An error occurred.
'OpenCV Error: Unspecified error (The function is not implemented.Rebuild the library with Windows, GTK + 2.x or Carbon support.If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, file /opencv-3.4.0/modules/highgui/src/window.cpp, line 611 '


Is there an error in the way I did it?

Also
Is it right to do 'python3 video_demo.py ./input' here?

**Comment by racsoraul** [comment]
@woojeonghoon 

The changes I made to the Dockerfile were applicable for Ubuntu/Debian only. 

> At this time
> An error occurred.
> 'OpenCV Error: Unspecified error (The function is not implemented.Rebuild the library with Windows, GTK + 2.x or Carbon support.If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, file /opencv-3.4.0/modules/highgui/src/window.cpp, line 611 '

From the above error, look a those lines:
-  **Rebuild the library with Windows, GTK + 2.x or Carbon support**
-  **If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config**

My changes to the Dockerfile were to **install libgtk2.0-dev and pkg-config** (second line above). You'll need to solve it for windows (first line).

> Is it right to do 'python3 video_demo.py ./input' here?

Is that last parameter a directory? It should be the video file.

**Comment by woojeonghoon** [comment]
@racsoraul

Thanks again for the answer.

My development environment is confirmed as Ubuntu 16.04
1 우분투버전

I checked if 'RUN apt-get install -y unzip wget libgtk2.0-dev pkg-config' is properly installed in Dockerfile-gpu.
2  lib 설치확인

3  pkg 설치확인

I tried various methods and it didn't work.

'https://answers.opencv.org/question/214718/cv2error-opencv410-cprojectsopencv-pythonopencvmoduleshighguisrcwindowcpp627-error-2unspecified-error-the-function-is-not-implemented/'
With reference to
I did 'pip3 install opencv-python'.

Then I typed 'python3 video_demo.py input / cat.mp4'

The history of the error has changed.
1오류

I didn't seem to be able to open a new screen.

Commented out 'cv2.imshow ("preview", frame)' in 'vi video_demo.py'.

Then it proceeded as follows and stopped.
2오류


Do you know anything about this...........?

**Comment by woojeonghoon** [comment]
@racsoraul
OH...............

I think
': cannot connect to X server' seems to be a problem with software called PUTTY.

I am trying to install a program called Xming.

By the way,
I'm not familiar with the Python source,

 When I run 'python3 video_demo.py input / dog.mp4', does a new window pop up to see the video change?


convert the video in the 'input folder'
I'm wondering how to save it to 'output folder'!

Like 'docker_demo.py'!

**Comment by woojeonghoon** [comment]
@racsoraul

excuse me ..... 

'docker demo.py'
like
files in the 'input' folder
If you want to convert it and put it in the 'output' folder

How should I modify 'video_demo.py'? TT

**Comment by madhawav** [comment]
Hi @racsoraul 
Very sorry for my delay!
I also tried running the code and came across the same issue discussed above with regard to cv2.imshow method. 
```bash
Loading weights from weights/yolov3.weights...Done!
Total Time: 0.7279760837554932 : 0.14559521675109863
No protocol specified

(preview:18): Gtk-WARNING **: cannot open display: :1
```

My host OS is Ubuntu 18.04 with Unity desktop environment.  Any work-around for this?

Also, I think its best to have docker-video demo launched from a separate shell script, instead of modifying the `run-gpu.sh` script.  We can have the modifications you have done for `run-gpu.sh` as a separate script `run-gpu-video.sh`.

**Comment by racsoraul** [comment]
Hi @madhawav!

I'm so sorry for my even longer delay.

Regarding the issue, this same PR adds two lines in the README: https://github.com/madhawav/YOLO3-4-Py/pull/80/files#diff-1e290ac8433d555bce009b162cb869d0R66-R67

I'll paste them here:
```
If you see the error `(preview:17): Gtk-WARNING **: cannot open display: :1`, you may solve it
by running `xhost +` in your host. Then, run the container again.
```

And yes, I agree with you regarding the script.

**Pull request closed without merging**
