### PR TITLE
Install numpy if it is not yet installed

### PR DESCRIPTION
**Pull request by mircearoata**

### CODE REVIEW

**Comment by h3ct0r** [comment]
Very useful!

**Comment by arielszabo** [comment]
I think a better solution is to add numpy directly to the requirements.txt file as in #103

**Comment by madhawav** [comment]
I can see that this solution should work. But, I think this could also over-ride the version of Numpy preferred by the user. For example, if a user runs 
```bash
pip install numpy=xx yolo34py```
would it install/link with the version of Numpy specified by the user?

**Comment by madhawav** [comment]
@arielszabo I accepted your PR, and missing Numpy at requirements file is indeed something I have over-looked. Thank you for showing it to me. However, adding Numpy to requirements file does not solve this issue.

**Comment by arielszabo** [comment]
@madhawav 
I'm not sure which issue you are referring to.
The Numpy version should be the one which works for your package, not the preferred one by the user, he should create a different virtual environment if it could break his other projects .

You should add the Numpy version to the requirements file (like this numpy==xxx), you can also use ">=" if you are sure Numpy won't break backwards compatibility.

**Comment by madhawav** [comment]
I see a couple of problems in installing Numpy manually as suggested in the pull request.
1) Wouldn't this approach install NumPy without the user's consent? Since we are manually calling pip install within the install script. 
2) The current pull request may not work with recent versions of Numpy as explained here: https://stackoverflow.com/questions/49870594/pip-main-install-fails-with-module-object-has-no-attribute-main

**Pull request closed without merging**
